version: '2.4'
services:
  influxdb:
    user: "${UID}:${GID}"
    image: influxdb:1.8.10
    restart: always
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      - "127.0.0.1:8086:8086"

  telegraf:
    user: "${UID}:${GID}"
    image: telegraf:1.21.2
    restart: always
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
      MQTT_SERVER: tcp://mosquitto:1883
      HOSTNAME:
      FRONIUS_LISTENER_ADDRESS:
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
      # Mounts for host monitoring
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
    ports:
      - "0.0.0.0:8090:8090"
    depends_on:
      - influxdb

  kapacitor:
    user: "${UID}:${GID}"
    image: kapacitor:1.6.3
    restart: always
    environment:
      - KAPACITOR_SMTP_ENABLED
      - KAPACITOR_SMTP_HOST
      - KAPACITOR_SMTP_PORT
      - KAPACITOR_SMTP_USERNAME
      - KAPACITOR_SMTP_PASSWORD 
      - KAPACITOR_SMTP_FROM
      - KAPACITOR_SMTP_TO_0
    volumes:
      # Mount for kapacitor data directory
      - ./kapacitor/data/:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - ./kapacitor/config/:/etc/kapacitor/

  chronograf:
    user: "${UID}:${GID}"
    image: chronograf:1.9.1
    restart: always
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
      CHRONOGRAF_ORGANIZATION:
      LOG_LEVEL: "error"
    volumes:
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
      # Mount for chronograf resources
      - ./chronograf/resources/:/usr/share/chronograf/resources/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "0.0.0.0:8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf

  mosquitto:
    user: "1883:1883"
    image: eclipse-mosquitto:2.0.14
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data/
    ports:
      - 0.0.0.0:1883:1883

volumes:
  mosquitto-data:
