version: '2.4'
services:
  influxdb:
    user: "${UID}:${GID}"
    image: influxdb:latest
    restart: always
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"

  telegraf:
    user: "${UID}:${GID}"
    image: telegraf:latest
    restart: always
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
      MQTT_SERVER: tcp://mosquitto:1883
      HOSTNAME:
      FRONIUS_LISTENER_ADDRESS:
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
      # Mounts for host monitoring
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
    ports:
      - "8090:8090"
    depends_on:
      - influxdb

  kapacitor:
    user: "${UID}:${GID}"
    image: kapacitor:latest
    restart: always
    environment:
      - KAPACITOR_SMTP_ENABLED
      - KAPACITOR_SMTP_HOST
      - KAPACITOR_SMTP_PORT
      - KAPACITOR_SMTP_USERNAME
      - KAPACITOR_SMTP_PASSWORD 
      - KAPACITOR_SMTP_FROM
      - KAPACITOR_SMTP_TO_0
    volumes:
      # Mount for kapacitor data directory
      - ./kapacitor/data/:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - ./kapacitor/config/:/etc/kapacitor/
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"

  chronograf:
    user: "${UID}:${GID}"
    image: chronograf:latest
    restart: always
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
      CHRONOGRAF_ORGANIZATION:
      LOG_LEVEL: "error"
    volumes:
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
      # Mount for chronograf resources
      - ./chronograf/resources/:/usr/share/chronograf/resources/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf

  mosquitto:
    user: "${UID}:${GID}"
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data/:/mosquitto/data/
    ports:
      - 1883:1883
